### ISSUE TITLE
Exception generated

### ISSUE THREAD

**Issue by mx5jon** [TreeFrogApps/MultiProcessPreferences#2]
I tried putting all the code files under my project, although it now complies. When the code runs it crashes with the following exception:

Unknown URI content://com.eurotimesystems.clockin.MultiProvider/string/Preferences_Name/testValue
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                    Caused by: java.lang.IllegalArgumentException: Unknown URI content://com.eurotimesystems.clockin.MultiProvider/string/Preferences_Name/testValue

**Comment by TreeFrogApps** [comment]
Hi, sorry 

The problem with the error is the provider uri, does `com.eurotimesystems.clockin.MultiProvider` match in two places

1) your `authorities` tag in the provider in the AndroidManifest.xml

2) in `MultiProvider.java` the `PROVIDER_NAME` should also be `com.eurotimesystems.clockin.MultiProvider`

The problem is should be that they should both match.
